### ISSUE TITLE
Will the pre-trained model be released?

### ISSUE THREAD

**Issue by int2char** [DelTA-Lab-IITK/shad3s#1]
Will the pre-trained model be released?

**Comment by bvraghav** [comment]
That's on our mind... Thanks for pointing it out...

**Comment by bvraghav** [comment]
As of now we have released the data. And the link is updated both on the [`README.md`](../blob/master/README.md) and on [the project page](https://bvraghav.com/shad3s/).

**Comment by bvraghav** [comment]
Updated on the links above.
