### ISSUE TITLE
Brushes?

### ISSUE THREAD

**Issue by petteriTeikari** [DelTA-Lab-IITK/shad3s#2]
Hi,

In your `test commands` you had a reference to the `--texture` `/nfs/151/gpu/raghav/data/shadegan/brushes_v2` but did not see those `brushes_v2` in the downloaded data tarball (https://bvraghav.com/shad3s/data.tar.xz)

**Comment by bvraghav** [comment]
Thanks for informing... I will get this done...

**Comment by bvraghav** [comment]
Sorry for the delay in response... But I have updated the link to brushes on the README as well as [project page](https://bvraghav.com/shad3s).
